site_name: 'angular-gantt'

site_url: http://www.angular-gantt.com
site_description: Gantt chart component for AngularJS

repo_url: https://github.com/angular-gantt/angular-gantt

theme: spacelab

pages:
- Home: index.md
- Get Started: get-started.md
- Configuration:
  - Data: configuration/data.md
  - Timespans: configuration/timespans.md
  - Attributes: configuration/attributes.md
  - Plugins: configuration/plugins.md
  - Customize: configuration/customize.md
  - API: configuration/api.md
  - Write a Plugin: configuration/write_plugin.md
- Plugins:
  - Sortable: plugins/sortable.md
  - Movable: plugins/movable.md
  - Draw Task: plugins/drawtask.md
  - Tooltips: plugins/tooltips.md
  - Bounds: plugins/bounds.md
  - Progress: plugins/progress.md
- Sources: sources.md
- Contribute: contribute.md
- FAQ: faq.md
- About: about.md



copyright: Copyright &copy; 2014, <a href="https://github.com/Schweigi">Marco Schweighauser</a>, <a href="https://twitter.com/Toilal">Rémi Alvergnat</a>.
